@SmokeTest
Feature: Prefence tab Verification

  Scenario: Verify Web.Properties in Prefence tab  
  Given I launch the browser for AdminConsole
  And I enter the credentials and verify the access for Adminconsole
  And I expand the ribbon bar for AdminConsole
  And I click on Preferences Settings tab and varify the options the properties values
  
  
   Scenario: Verify Prefence tab Values in Web.Properties 
  Given I launch the browser for AdminConsole
  And I enter the credentials and verify the access for Adminconsole
  And I expand the ribbon bar for AdminConsole
  And I click on Preferences Settings tab and varify the Web properties values