
@UXTesting
Feature: UX Testing

Scenario: Launch the HACP EE Page
#Login Page
Given I Launch the Browser and enter the url
When I Check the Font and Colour For HACP EE
Then I check the Header Colour For HACP EE
Then I Check the Backgorund Colour For HACP EE
Then I Check the Login Panel Colour
Then I check the Username font and Colour
Then I Check the password Font and Colour
Then I Check the Input Field Colour
Then I Check Remberme Font and colour
Then I Check the Login Font and Colour
Then I Check the Copyright Details
Then I Check the Error Messages

#Guest Connect
Then I Check the Continue as guest Font and colour
Then I Check the Guest Connect Background colour
Then I Check the Guest Connect Title Font and Colour
Then I Check the Guest connect Heading Font and Colour
Then I Check the Guest Connect SubHeading Font and Colour
Then I Check the Field Disable Background Colour
Then I Check the Input Field Background Colour
Then I Check the Connect Font, colour and ConnectButton BAckground Colour

#Dashboard
Then I Check the Active session font and colour
Then I Check the Available Session Font anc Colour
Then I Check the Session Name FOnt and Colour
Then I Check the search bar background colour

#About Panel
Then I Check the About Panel Footer Colour
Then I Check the About Panel Header Colour
Then I CHeck the About Heading Font and Colour
Then I Check the About Content Font and Colour
Then I Check the About Panel Close Background Colour

#Property Panel
Then I Check the PropertyPanel Heading
Then I Check the current Panel Font and colour
Then I Check the Other Panel Font and Colour
Then I Check the Property Panel Sub Menu Font and Colour
Then I CHeck the Property Panel Background colour
Then I Check the Property Panel Footer Colour
Then I Check the Property Panel Savebutton
Then I Check the Property Panel CancelButton


